# Generated by Django 4.1.7 on 2023-06-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stan',
            fields=[
                ('st_TowId', models.IntegerField(primary_key=True, serialize=False)),
                ('st_MagId', models.IntegerField(db_column='st_MagId')),
                ('st_Stan', models.FloatField(db_column='st_Stan', max_length=8)),
            ],
            options={
                'db_table': '[dbo].[tw_Stan]',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Towar',
            fields=[
                ('tw_Id', models.IntegerField(db_column='tw_Id', primary_key=True, serialize=False)),
                ('tw_Nazwa', models.CharField(db_column='tw_Nazwa', max_length=45)),
                ('tw_Symbol', models.CharField(db_column='tw_Symbol', max_length=13)),
                ('tw_PodstKodKresk', models.CharField(blank=True, db_column='tw_PodstKodKresk', max_length=20)),
                ('stan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.stan')),
            ],
            options={
                'db_table': '[dbo].[tw__Towar]',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('zd_Id', models.IntegerField(db_column='zd_Id', primary_key=True, serialize=False)),
                ('zd_Zdjecie', models.ImageField(blank=True, upload_to='')),
                ('zd_Glowne', models.BinaryField(max_length='max')),
                ('zd_CRC', models.IntegerField(blank=True)),
                ('zd_IdTowar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.towar')),
            ],
            options={
                'db_table': '[dbo].[tw_ZdjecieTw]',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_Nazwa', models.CharField(max_length=50)),
                ('mag_Id', models.ManyToManyField(to='app.stan')),
            ],
            options={
                'db_table': '[dbo].[sl_Magazyn]',
                'managed': True,
            },
        ),
    ]
