# Generated by Django 4.1.7 on 2023-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_zdjecie_zd_idtowar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='magazyn',
            table='sl_Magazyn',
        ),
        migrations.AlterModelTable(
            name='stan',
            table='tw_Stan',
        ),
        migrations.AlterModelTable(
            name='towar',
            table='tw__Towar',
        ),
        migrations.AlterModelTable(
            name='zdjecie',
            table='tw_ZdjecieTw',
        ),
    ]
