# Generated by Django 4.1.7 on 2023-06-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stan_st_towid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towar',
            name='stan',
        ),
    ]
