# Generated by Django 4.1.7 on 2023-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_towar_stan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_IdTowar',
            field=models.IntegerField(db_column='zd_IdTowar'),
        ),
    ]
