# Generated by Django 4.1.7 on 2023-06-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_zdjecie_zd_idtowar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_CRC',
            field=models.IntegerField(blank=True, db_column='zd_CRC'),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_Glowne',
            field=models.BinaryField(db_column='zd_Glowne', max_length='max'),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_Zdjecie',
            field=models.ImageField(blank=True, db_column='zd_Zdjecie', upload_to=''),
        ),
    ]
