# Generated by Django 4.1.7 on 2023-06-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_zdjecie_zd_crc_alter_zdjecie_zd_glowne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_Glowne',
            field=models.BooleanField(db_column='zd_Glowne'),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_IdTowar',
            field=models.ForeignKey(db_column='zd_IdTowar', on_delete=django.db.models.deletion.DO_NOTHING, to='app.towar'),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_Zdjecie',
            field=models.BinaryField(blank=True, db_column='zd_Zdjecie', max_length='max', null=True),
        ),
    ]
