# Generated by Django 4.1.7 on 2023-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_zdjecie_zd_glowne_alter_zdjecie_zd_idtowar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='zd_Zdjecie',
            field=models.ImageField(blank=True, db_column='zd_Zdjecie', null=True, upload_to=''),
        ),
    ]
