# Generated by Django 4.1.7 on 2023-06-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_zdjecie_zd_zdjecie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwKodkreskowy',
            fields=[
                ('kk_id', models.IntegerField(db_column='kk_Id', primary_key=True, serialize=False)),
                ('kk_kod', models.CharField(db_column='kk_Kod', max_length=20)),
                ('kk_ilosc', models.DecimalField(blank=True, db_column='kk_Ilosc', decimal_places=4, max_digits=19, null=True)),
                ('kk_idtowar', models.ForeignKey(db_column='kk_IdTowar', on_delete=django.db.models.deletion.DO_NOTHING, to='app.towar')),
            ],
            options={
                'db_table': 'tw_KodKreskowy',
                'managed': True,
                'unique_together': {('kk_idtowar', 'kk_kod')},
            },
        ),
    ]
