# Generated by Django 4.1.7 on 2023-06-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_twkodkreskowy_kodkreskowy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kodkreskowy',
            unique_together=set(),
        ),
    ]
