# Generated by Django 4.1.7 on 2023-06-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_kodkreskowy_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kodkreskowy',
            options={'managed': False},
        ),
    ]
