# Generated by Django 4.1.7 on 2023-06-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_kodkreskowy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kodkreskowy',
            options={'managed': False},
        ),
    ]
