# Generated by Django 4.1.7 on 2023-06-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_kodkreskowy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kodkreskowy',
            options={'managed': True},
        ),
    ]
