# Generated by Django 4.1.7 on 2023-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_kodkreskowy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodkreskowy',
            name='kk_idtowar',
            field=models.IntegerField(db_column='kk_IdTowar'),
        ),
    ]
