# Generated by Django 4.1.7 on 2023-06-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_kodkreskowy_kk_idtowar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kodkreskowy',
            name='kk_idtowar',
            field=models.ForeignKey(db_column='kk_IdTowar', on_delete=django.db.models.deletion.DO_NOTHING, to='app.towar'),
        ),
    ]
