# Generated by Django 4.1.7 on 2023-06-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_kodkreskowy_kk_idtowar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kodkreskowy',
            new_name='Ean',
        ),
    ]
